// Generated by CoffeeScript 1.3.3

define(["jquery"], function() {
  var Controller;
  return Controller = (function() {

    function Controller(view) {
      this.view = view;
    }

    Controller.prototype.load = function() {
      return this.view.show();
    };

    Controller.prototype.unload = function() {
      return this.view.hide();
    };

    return Controller;

  })();
});
