// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "application/controllers/controller"], function($, Controller) {
  var loadingController;
  return loadingController = (function(_super) {

    __extends(loadingController, _super);

    function loadingController(view) {
      this.view = view;
      loadingController.__super__.constructor.call(this, this.view);
    }

    loadingController.prototype.load = function() {
      return loadingController.__super__.load.call(this);
    };

    loadingController.prototype.unload = function() {
      return loadingController.__super__.unload.call(this);
    };

    return loadingController;

  })(Controller);
});
