// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "application/controllers/controller", "application/models/api"], function($, Controller, RtbfApi) {
  var loadingController;
  return loadingController = (function(_super) {

    __extends(loadingController, _super);

    function loadingController(view, api) {
      this.view = view;
      this.api = api;
      loadingController.__super__.constructor.call(this, this.view);
    }

    loadingController.prototype.load = function() {
      console.log("Loading controller load");
      loadingController.__super__.load.call(this);
      console.log("Gonna get data");
      return this.api.fetchData();
    };

    loadingController.prototype.unload = function() {
      return loadingController.__super__.unload.call(this);
    };

    return loadingController;

  })(Controller);
});
