// Generated by CoffeeScript 1.3.3

define(["jquery"], function($) {
  var mainController;
  return mainController = (function() {

    function mainController() {}

    return mainController;

  })();
});
