// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "application/controllers/controller"], function($, Controller) {
  var screen1Controller;
  return screen1Controller = (function(_super) {

    __extends(screen1Controller, _super);

    function screen1Controller(view, api) {
      this.view = view;
      this.api = api;
      screen1Controller.__super__.constructor.call(this, this.view);
    }

    screen1Controller.prototype.activate = function() {
      this.data = this.api.getData();
      this.view.setData(this.data);
      console.log("data screen1:");
      console.log(this.data);
      return screen1Controller.__super__.activate.call(this);
    };

    screen1Controller.prototype.unload = function() {};

    return screen1Controller;

  })(Controller);
});
