// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var screen1Controller;
  return screen1Controller = (function() {

    function screen1Controller(view) {
      this.view = view;
      console.log("Screen1 controller created");
    }

    screen1Controller.prototype.load = function() {
      console.log("load called");
      return this.view.show();
    };

    screen1Controller.prototype.unload = function() {
      return this.view.hide();
    };

    return screen1Controller;

  })();
});
