// Generated by CoffeeScript 1.3.3

define(["jquery", "application/controllers/main"], function($, mainController) {
  var Application;
  return Application = (function() {

    function Application() {}

    Application.prototype.init = function() {
      return console.log("Application initialized");
    };

    return Application;

  })();
});
