// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var loadingScreenView;
  return loadingScreenView = (function() {

    function loadingScreenView(divID) {
      this.divID = divID;
      console.log("Loading view with id: " + divID);
    }

    loadingScreenView.prototype.show = function() {
      return $("" + this.divID).show();
    };

    loadingScreenView.prototype.hide = function() {
      return $("" + this.divID).hide();
    };

    return loadingScreenView;

  })();
});
