// Generated by CoffeeScript 1.4.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["jquery", "underscore", "application/views/screen", "vendor/jquery/jquery.flot", "vendor/jquery/jquery.flot.time"], function($, _, ScreenView, jQueryFlot, jQueryFlotTime) {
  var screen1ScreenView;
  return screen1ScreenView = (function(_super) {

    __extends(screen1ScreenView, _super);

    screen1ScreenView.prototype.getItemTemplate = function() {
      return "<li class=\"item\">\n  <span class=\"title\"><%= title %></span><span class=\"value\"><%= value %></span>\n</li>";
    };

    function screen1ScreenView(divID) {
      this.divID = divID;
      screen1ScreenView.__super__.constructor.call(this, this.divID);
    }

    screen1ScreenView.prototype.show = function() {
      var html;
      html = this.parseTemplate();
      console.log(html);
      $("" + this.divID + " .list").html(html);
      this.displayGraph();
      return screen1ScreenView.__super__.show.call(this);
    };

    screen1ScreenView.prototype.parseTemplate = function() {
      var item, liItem, list, template;
      template = this.getItemTemplate();
      if (this.data && this.data.length > 0) {
        return list = (function() {
          var _i, _len, _ref, _results;
          _ref = this.data;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            item = _ref[_i];
            liItem = {
              title: item.name,
              value: item.value
            };
            _results.push(_.template(template, liItem));
          }
          return _results;
        }).call(this);
      }
    };

    screen1ScreenView.prototype.displayGraph = function() {
      var options, placeholder, seriesData;
      seriesData = this.data;
      placeholder = $("" + this.divID + " .graph");
      options = {
        lines: {
          show: true
        },
        points: {
          show: true
        },
        xaxis: {
          mode: "time"
        }
      };
      return $.plot(placeholder, seriesData, options);
    };

    return screen1ScreenView;

  })(ScreenView);
});
