// Generated by CoffeeScript 1.3.3

define(["jquery", "application/controllers/loading", "application/views/loadingScreen", "application/controllers/screen1", "application/views/screen1Screen", "application/models/input"], function($, loadingController, loadingView, screen1Controller, screen1View, Input) {
  var Application;
  return Application = (function() {

    function Application() {}

    Application.prototype.init = function() {
      var _this = this;
      this.loadingController = new loadingController(new loadingView("#loading"));
      this.loadingController.load();
      this.screen1Controller = new screen1Controller(new screen1View("#screen1"));
      this.screen1Controller.unload();
      console.log("Application initialized...");
      $('body').bind('keydown', function(e) {
        return _this.dispatch(Input.keyEventToEvent(e));
      });
      return $('body').bind('AppEvent', function(e, action) {
        return _this.dispatch(action);
      });
    };

    Application.prototype.dispatch = function(e) {
      console.log("dispatch received:");
      console.log(e);
      switch (e) {
        case 'LOADED':
          this.loadingController.unload();
          return this.screen1Controller.load();
        case 'KEY_UP':
          return $('body').trigger('AppEvent', ['LOADED']);
      }
    };

    return Application;

  })();
});
