// Generated by CoffeeScript 1.3.3

define([], function() {
  var Input;
  return Input = (function() {

    function Input() {}

    Input.keyEventToEvent = function(e) {
      var key;
      key = e.which;
      switch (key) {
        case 37:
          return 'KEY_LEFT';
        case 38:
          return 'KEY_UP';
        case 39:
          return 'KEY_RIGHT';
        case 40:
          return 'KEY_DOWN';
      }
    };

    return Input;

  })();
});
