// Generated by CoffeeScript 1.4.0

define(["jquery"], function($) {
  var StateMachine;
  return StateMachine = (function() {

    function StateMachine() {}

    StateMachine.prototype.add = function(controller) {
      this.bind("change", function(e, current) {
        if (controller === current) {
          return controller.activate();
        } else {
          return controller.deactivate();
        }
      });
      return controller.active = $.proxy(function() {
        return this.trigger("change", controller);
      });
    };

    StateMachine.prototype.bind = function() {
      var _ref;
      if ((_ref = this.o) == null) {
        this.o = $({});
      }
      return this.o.bind.apply(this.o, arguments);
    };

    StateMachine.prototype.trigger = function() {
      var _ref;
      if ((_ref = this.o) == null) {
        this.o = $({});
      }
      return this.o.trigger.apply(this.o, arguments);
    };

    return StateMachine;

  })();
});
